Header header

# average period 
float64 PeriodAvg
# deviation on periodicity
float64 PeriodStdDev
# min and max time between
float64 PeriodMin
float64 PeriodMax
# same 4 values for compute time
float64 ComputeTimeAvg
float64 ComputeTimeStdDev
float64 ComputeTimeMin
float64 ComputeTimeMax
# number of samples used to compute these status
int64 NumberOfSamples
# number of overruns base on previous interval average
int64 NumberOfOverruns
# time window covered by these stats
float64 StatisticsInterval

# user data
int64 UserData
